apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envanter
  namespace: infra
spec:
  project: default
  source:
    repoURL: https://github.com/bhaslaman/Envanter_App.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: envanter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
