apiVersion: v1
kind: ConfigMap
metadata:
  name: envanter-config
  namespace: envanter
data:
  ENVANTER_ADDR: ":8080"
  ENVANTER_LOG_LEVEL: "info"
  ENVANTER_DB_URL: "postgres://envanter:envanter_dev@postgres:5432/envanter?sslmode=disable"
  ENVANTER_SMTP_HOST: "mailhog"
  ENVANTER_SMTP_PORT: "1025"
  ENVANTER_SMTP_FROM: "noreply@envanter.local"
