apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Local Docker Desktop overlay — ingress, network-policy ve sealed-secret yok.
resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres.yaml
- minio.yaml
- api.yaml
- web.yaml
- adminer.yaml
- mailhog.yaml

images:
- name: ghcr.io/gameofai/envanter-api
  newTag: main-f5347df
- name: ghcr.io/gameofai/envanter-web
  newTag: main-f5347df
